[build]
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_APP_URL"
  NODE_VERSION = "18"

# Install Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/_next/image"
  query = { q = ":quality", url = ":url", w = ":width" }
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200

[[redirects]]
  from = "/_ipx/*"
  query = { q = ":quality", url = ":url", w = ":width" }
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
